### ISSUE TITLE
Python library upgrades

### ISSUE THREAD

**Issue by alimanfoo** [cggh/biipy#24]
The following libraries can be upgraded:
- cython (0.24)
- numpy (1.11.0)
- lxml (3.6.0)
- scipy (0.17.0)
- pandas (0.18.0)
- numexpr (2.5.2)
- llvmlite (0.10.0)
- numba (0.25.0)
- `ipython[all]` (4.2.0)
- h5py (2.6.0)
- bcolz (1.0.0)
- rpy2 (2.7.8)
- scikit-learn (0.17.1)
- bokeh (0.11.1)
- dask (0.8.2)
- zarr (0.4.0)
- msprime (0.1.10)
- psutil (4.1.0)

Note that a newer version of pysam is also available however we shouldn't upgrade at this time because it would break compatibility with pysamstats.

**Comment by hardingnj** [comment]
Done in newest commit, with exception of numpy which stays at 1.10.0 as anaconda.
