### ISSUE TITLE
font errors

### ISSUE THREAD

**Issue by hardingnj** [cggh/biipy#31]
This has been bugging me for a while... but I have been getting errors when I run a notebook by @alimanfoo . 

I looked into it today and it seems to be this line that causes the issue:

`rcParams['font.family'] = 'arial'`

For some reason my container doesn't have that font installed. However I can't tell the default from arial. I'll look into how to install a missing font that mpl has access too. The fact that this runs in @alimanfoo 's biipy makes me think it is a system display issue?

**Comment by alimanfoo** [comment]
I haven't tried this in latest biipy, maybe the microsoft ttf fonts are no
longer installed? Btw I'm not sure it is necessary any more, the default
ubuntu sans-serif is probably indistinguishable and perfectly good.

On Wed, Jun 15, 2016 at 2:09 PM, Nick Harding notifications@github.com
wrote:

> This has been bugging me for a while... but I have been getting errors
> when I run a notebook by @alimanfoo https://github.com/alimanfoo .
> 
> I looked into it today and it seems to be this line that causes the issue:
> 
> #rcParams['font.family'] = 'arial'
> 
> For some reason my container doesn't have that font installed. However I
> can't tell the default from arial. I'll look into how to install a missing
> font that mpl has access too. The fact that this runs in @alimanfoo
> https://github.com/alimanfoo 's biipy makes me think it is a system
> display issue?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/cggh/biipy/issues/31, or mute the thread
> https://github.com/notifications/unsubscribe/AAq8Qsg7Ij4hKiRCb8AUwKVTvRb6qyFqks5qL_lvgaJpZM4I2VmB
> .

## 

Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health http://cggh.org
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Email: alimanfoo@googlemail.com alimanfoo@gmail.com
Web: http://purl.org/net/aliman
Twitter: https://twitter.com/alimanfoo
Tel: +44 (0)1865 287721

**Comment by hardingnj** [comment]
Closing- can fix problem by removing above line.
